### ISSUE TITLE
Running the extension in Revit crashes Revit

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoWorkspaceUpgradeExtension#6] opened 2018-04-14 20:00 UTC
@mjkkirschner I let Revit send the crash report and wrote in the comments to forward the data to you.

**Comment by mjkkirschner** [comment] 2018-04-15 16:25
hmm, I assume it will take a while for that to find me, did it crash with other revit versions or just that one?

**Comment by andydandy74** [comment] 2018-04-15 17:31
Will double-check on both work and home computer and let you know my findings.

**Comment by andydandy74** [comment] 2018-04-15 22:19
@mjkkirschner I can now confirm that this happens on multiple computers, both for Revit 2017.2.3 and Revit 2018.3 :-(
Find journal files here: https://github.com/andydandy74/MyIssues/tree/master/DynamoWorkspaceUpgradeExtension6
This is what gets logged right after clicking the Migrate button:
```
Managed exception occurred: 
WPF RenderMode set to: SoftwareOnly
Collection was modified; enumeration operation may not execute. 
ExceptionCode=0xe0434352 ExceptionFlags=0x00000001 ExceptionAddress=00007FFAF3A44008 
```
And shortly after the journal end with this:
```
unhandledExceptionFilter is executed in a non-main thread (id = 8668, tag = <blank> : [was TaskFileExists]).
```
I was running the latest daily build (DynamoCore 2.0.0.4654, DynamoRevit 2.0.0.4655).

**Comment by mjkkirschner** [comment] 2018-04-15 22:43
thanks @andydandy74 - this exception helps.

**Comment by Racel** [comment] 2018-04-16 14:37
@andydandy74 - Can you consistently reproduce this? Is it only happening on particular files? Can you please provide files and steps to reproduce?

**Comment by andydandy74** [comment] 2018-04-17 04:33
I tried converting the entire Clockwork package in one go. Here's what I did:
- Copy all nodes from the repo (https://github.com/andydandy74/ClockworkForDynamo/tree/master/nodes/1.x) to a temporary folder
- Start Revit
- Open Basic Arch. sample model that ships with Revit
- Start DynamoRevit
- Start Migrator Extension from Views Menu
- Specify source path
- Hit Migrate button

In Revit 2017.2.3 the extension managed to convert some 152 nodes before crashing, in Revit 2018.3 it stopped at 157 nodes. (These numbers vary on each run, though.) Memory usage kept rising fairly constantly but was "only" at ~75% at the time of the crash. Also, the crash / exception is not always recorded in the journal.

**Comment by kronz** [comment] 2018-04-20 16:55
Any change in behavior if you change the graphic hardware settings in Revit?  My recollection is that this also changes the Softare or Hardware based rendering of Dynamo
![2018-04-20_1253](https://user-images.githubusercontent.com/3456818/39063717-f55f8bc0-4499-11e8-828e-05a865b22808.png)

**Comment by andydandy74** [comment] 2018-04-20 17:40
Makes no difference. :-(

**Comment by Racel** [comment] 2018-04-27 16:04
@mjkkirschner Did we file a task to fix this? If not, can you please file?

**Comment by mjkkirschner** [comment] 2018-04-27 16:33
@Racel now tracked with: https://jira.autodesk.com/browse/QNTM-4168

**Comment by mjkkirschner** [comment] 2018-04-27 16:39
@andydandy74 ... would you mind trying this after removing the library extension from the viewExtensions folder of your dynamo core install?

**Comment by andydandy74** [comment] 2018-04-28 09:18
That seems to be working better, at least it doesn't crash any more. The first 220 or so nodes were done in 5 minutes. By that time Revit had used up all of my machine's memory. 8 hours later another 80 nodes were done. The next 90 minutes DynamoRevit was unresponsive and I finally terminated the Revit process. Disposing of the ```dynamoViewModel``` object after each file is saved doesn't help either.

**Comment by mjkkirschner** [comment] 2018-04-28 14:45
@ramramps @jnealb @smangarole - @andydandy74 has tried again and removed library, this has prevented the collection modified crash.

@ jnealb -seems you can use this extension and clockwork 1.x to reproduce the crash.

**Comment by jnealb** [comment] 2018-04-28 20:25
Will take a look: as the migration runs Revit process memory usage grows monotonically (in big chunks) and then Revit crashes. This is tracked with QNTM-4179; thanks @andydandy74.

**Comment by jnealb** [comment] 2018-05-01 21:36
@mjkkirschner @andydandy74 We can reproduce the crash, please see updated QNTM-4179 and QNTM-4194 for details.

**Comment by DanimoSite** [comment] 2018-06-04 14:05
Hi all,

Was going to flag this up but seems @andydandy74 has already go there.

I am also getting a similar problem with revit 2017/2018. I initially wrote my own VE and got some crashes and then used this upgrader, but same result.

I have tried on multiple packages (funny enough, clockwork was my first test due to it's high usage in our workplace and that it is one of the largest packages). But couldn't see any obvious reasons for it, and the crash doesn't always land on the same file. Also, Revit 2017 flags an error has occured and the AD form to submit an issue but then continues to run and bombs 170 in. Revit 2018 bombed on run right away. Pulled all the packages paths from library and repathed to just clockwork, this worked more consistently between Revit versions, but consistently crashes about 80-100 in. I get the same results when trying to upgrade our internal packages too, there are about 200 .dyf files and gets about 50 in before the crash.

Would be great if there was a fix for this as this is a very useful tool.

Many thanks,
Dan

**Comment by mjkkirschner** [comment] 2018-06-04 14:19
@DanimoSite try actually removing the library extension from your viewExtensions folder in the dynamoCore root directory. You will then probably make it the furthest before a memory leak causes the crash, which should be much later along than the collection modified crash.

I have not had time to investigate either of them yet, but did fix a bunch of memory leaks in workspace model between 1.3 and 2.0 - guess I missed some.

**Comment by DanimoSite** [comment] 2018-06-04 15:57
Hi @mjkkirschner,

Yup, this is working a lot better now stormed through about 280 of them in 5 mins similar to the thread above, but I now see what you mean about memory, Revit is taking up about 85% of my memory. I will try do in batches maybe.

Cheers,
Dan

**Comment by andydandy74** [comment] 2018-06-04 16:29
FWIW I just divided my nodes up into equal batches that I knew the extension would be able to handle. That worked well enough for me. I was able to migrate Clockwork in 4 runs. Definitely beats manual labour. 😏

**Comment by DanimoSite** [comment] 2018-06-04 16:49
Ha! Yup! Certainly does. Even better, I can just download your updated 2.0 package! 😜

**Comment by andydandy74** [comment] 2018-06-04 16:53
It's not entirely tested yet. Still need to go through the Tesselation and Revit nodes. Hoping to publish it next week.

**Comment by DanimoSite** [comment] 2018-06-04 17:18
Sweet. Roughly about the time I'm rolling out 2.0 to our lads and ladies and I've upgraded everything else. I'll keep an eye out for the update!

**Closed as completed** 2019-09-07 19:01 UTC
